<a href="https://colab.research.google.com/github/wndjs319-wq/2025-LLM/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_4%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a = np.arange(1, 13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [8]:
np.column_stack( (a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
np.column_stack( (a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
x

array([[1, 2, 3]])

In [18]:
y

array([[4, 5, 6]])

In [19]:
x.shape, y.shape

((1, 3), (1, 3))

In [20]:
np.column_stack( (x, y) )

array([[1, 2, 3, 4, 5, 6]])

In [21]:
np.c_[x ,y]

array([[1, 2, 3, 4, 5, 6]])

In [23]:
np.c_[x , 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [24]:
np.column_stack ( (x, 10 ,20 ,y) )

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [31]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7CA3D17DACE0

In [34]:
import numpy as np
rg = np.random.default_rng(12345)
rg.random()

0.22733602246716966

In [39]:
rg.random()

0.33281392786638453

In [40]:
rg.random(5)

array([0.59830875, 0.18673419, 0.67275604, 0.94180287, 0.24824571])

In [44]:
rg.random((4,3))

array([[0.94888115, 0.66723745, 0.09589794],
       [0.44183967, 0.88647992, 0.6974535 ],
       [0.32647286, 0.73392816, 0.22013496],
       [0.08159457, 0.1598956 , 0.34010018]])

In [53]:
import numpy as np
rg = np.random.default_rng(1)
rg.integers(low=0,high=10,size=3)

array([4, 5, 7])

In [58]:
rg.integers(0,high=20,size=(3,4))

array([[ 5,  0, 15,  1],
       [ 5,  9,  9,  2],
       [19, 14, 19,  1]])

In [59]:
import numpy as np
rg = np.random.default_rng(1)
rg.standard_normal(10) # 표준 정규분포 실수 난수

array([ 0.34558419,  0.82161814,  0.33043708, -1.30315723,  0.90535587,
        0.44637457, -0.53695324,  0.5811181 ,  0.3645724 ,  0.2941325 ])

In [62]:
rg.standard_normal((3,4))

array([[ 0.00814218, -0.27560291,  1.29406381,  1.00672432],
       [-2.71116248, -1.88901325, -0.17477209, -0.42219041],
       [ 0.213643  ,  0.21732193,  2.11783876, -1.11202076]])

#배열 결합 연습

In [64]:
a= np.arange(1,4)
b= np.arange(4,7)
c= np.arange(7,10)
a,b,c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [70]:
p= np.arange(1,7).reshape(2,3)
q= np.arange(11,17).reshape(2,3)
r= np.arange(21,27).reshape(2,3)
p,q,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [72]:
np.vstack((a,b,c)) # 10 --> 20

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.vstack((p,q,r))  # 20 -->20

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [74]:
np.hstack((a,b,c)) # 10 --> 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.hstack((p,q,r)) # 20 --> 20

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [78]:
np.column_stack((a,b,c)) # 10 --> 20

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [79]:
np.column_stack((p,q,r)) # 20 --> 20

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [80]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.concatenate((a,b,c),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [83]:
np.concatenate((a,b,c),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.concatenate((a,b,c),axis = -1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.concatenate((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [90]:
np.concatenate((p,q,r),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [91]:
p ,q ,r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [92]:
np.concatenate((p,q,r),axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [93]:
np.concatenate((p,q,r),axis=-1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [94]:
np.concatenate((p,q,r),axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [95]:
np.c_[a,b,c] # 10-->10

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [96]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [97]:
np.c_[p,q,r] # 20-->20

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [98]:
np.r_[a,b,c] # 10-->10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.r_[p,q,r] # 20-->20

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [100]:
np.concatenate((p,q,r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])